language: python

sudo: required

dist: xenial

python:
- '3.6'

jobs:
  include:
    stage: e2e-stories-serpentbot
    python: "3.6"
    install:
      - sudo apt-get install -y pkg-config libxml2-dev libxmlsec1-dev libxmlsec1-openssl libpq-dev
      - pip install -r requirements.txt
    script:
      - rasa train
      - rasa test --stories test_stories/stories.md --e2e --fail-on-prediction-errors