language: en
pipeline:
- name: WhitespaceTokenizer
  intent_split_symbol: _
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
- name: ResponseSelector
- name: RegexFeaturizer
- name: EntitySynonymMapper
- name: CRFEntityExtractor
  features:
  - - low
    - title
    - upper
  - - bias
    - low
    - prefix5
    - prefix2
    - suffix5
    - suffix3
    - suffix2
    - upper
    - title
    - digit
    - pattern
  - - low
    - title
    - upper
policies:
- name: AugmentedMemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
